---
- hosts: cloudport
  vars_files:
    - ../vars/application.yml
    - ../vars/secrets.yml
  vars:
    bundler_cmd: ". {{ app_conf_file }} && bundle"
    db_created_flag: "{{ app_user_home }}/.db_created"
    db_schema_loaded_flag: "{{ app_user_home }}/.db_schema_loaded"
  become: yes
  become_user: "{{ app_user_name }}"
  tasks:
    - name: Get p.t.u. code from Git
      git: repo={{ ptu_repo }}
           dest={{ ptu_path }}
           version={{ ptu_version }}
           force=yes
      notify:
        - Install p.t.u. dependencies
        - Create p.t.u. tarball from repo
        - Checkout working version of ssh package
    - name: Get application code from Git
      git: repo={{ app_repo }}
           dest={{ app_path }}
           version={{ app_version }}
           force=yes
      notify:
        - Bundle install
        - Create database
        - Load database schema
        - Run database migrations
        - Pull Docker [base] image
        - 3rd party assets
        - Reload application server
  handlers:
    - name: Install p.t.u. dependencies
      shell: ". {{ app_conf_file }} && script/install"
      args:
        chdir: "{{ ptu_path }}"
    - name: Create p.t.u. tarball from repo
      shell: "tar -C {{ ptu_path }} -c . -f {{ ptu_path }}.tar"
      args:
        warn: no
    - name: Checkout working version of ssh package
      shell: "git checkout 459e26527287adbc2adcc5d0d49abff9a5f315a7"
      args:
        chdir: "{{ app_user_home }}/go/1.7.1/src/golang.org/x/crypto/ssh"
        warn: no
    - name: Bundle install
      shell: "{{ bundler_cmd }} install --retry=5 --deployment --without '{{ bundle_without }}'"
      args:
        chdir: "{{ app_path }}"
        warn: no
    - name: Create database
      shell: "{{ bundler_cmd }} exec rake db:create && touch {{ db_created_flag }}"
      args:
        chdir: "{{ app_path }}"
        creates: "{{ db_created_flag }}"
    - name: Load database schema
      shell: "{{ bundler_cmd }} exec rake db:schema:load && touch {{ db_schema_loaded_flag }}"
      args:
        chdir: "{{ app_path }}"
        creates: "{{ db_schema_loaded_flag }}"
    - name: Run database migrations
      shell: "{{ bundler_cmd }} exec rake db:migrate"
      args:
        chdir: "{{ app_path }}"
    - name: Pull Docker [base] image
      shell: "{{ bundler_cmd }} exec rake docker:images:pull"
      args:
        chdir: "{{ app_path }}"
    - name: 3rd party assets
      shell: "{{ app_path }}/script/tools/download-{{ item }} >/dev/null"
      args:
        chdir: "{{ app_path }}"
      with_items:
        - extjs
        - icons
    - name: Reload application server
      shell: "sudo {{ app_reload_script }}"
      args:
        warn: no
