#!/usr/bin/env ruby
#
# Generate secrets.yml [if it does not exist] for use with Ansible
#
require 'securerandom'
require 'yaml'

SECRETS_FILE = File.expand_path(File.dirname(__FILE__) + '/../ansible/vars/secrets.yml')

unless File.exist?(SECRETS_FILE)
  SECRETS = {
    'mysql_root_password' => SecureRandom.base64,
    'mysql_app_password'  => SecureRandom.base64,
    'secret_key_base'     => SecureRandom.hex(64),
    'web_admin_password'  => 'portcloud',
  }

  File.open(SECRETS_FILE, 'w') {|f| f.write SECRETS.to_yaml }
end

puts SECRETS_FILE
