#!/usr/bin/env bash
#
# perform full provisioning || deploy code
#
if [ ${#} -ne 1 ]; then
  echo "Usage: ${0} DEPLOY_ENV"
  echo
  echo "DEPLOY_ENV := { local | production | staging | [ANYTHING] }"
  echo
  echo "HINT: 'local' is a production environment used on localhost"
  exit 1
fi

declare -r DEPLOY_ENV=${1}
declare -r HOSTS_FILE=/etc/ansible/${DEPLOY_ENV}
declare -r PLAYBOOK_FILE="$(dirname $0)/../ansible/$(basename ${0}).yml"
declare -r APP_VERSION="$(git rev-parse --abbrev-ref HEAD)"

echo
echo "* Deploy: ${APP_VERSION}"
echo

set -e

source $(dirname $0)/_bootstrap.sh # bootstrap system [for given deploy environment]
$(dirname $0)/dump-secrets-file    # generate secrets file [if it does not exist]

if [[ "${DEPLOY_ENV}" == "local" ]]; then
  ansible-playbook -c local -i "$(dirname $0)/../ansible/hosts.local" -e app_version=${APP_VERSION} ${PLAYBOOK_FILE}
else
  ansible-playbook -i ${HOSTS_FILE} -e app_version=${APP_VERSION} ${PLAYBOOK_FILE}
fi
