#!/usr/bin/env bash
#
# perform full provisioning || deploy code
#
if [ $# -ne 1 ]; then
  echo "Usage: ${0} DEPLOY_ENV"
  exit 1
fi

DEPLOY_ENV=${1}
HOSTS_FILE=/etc/ansible/${DEPLOY_ENV}

$(dirname $0)/ensure-secrets-file # generate secrets file [if does not exist]

if [ "${DEPLOY_ENV}" == "production" ]; then
  APP_VERSION="master"
else
  APP_VERSION="develop"
fi

PLAYBOOK_FILE="$(dirname $0)/../ansible/$(basename ${0}).yml"

ansible-playbook -i ${HOSTS_FILE} -e app_version=${APP_VERSION} ${PLAYBOOK_FILE}
