#!/usr/bin/env bash
#
# perform full provisioning || deploy code
#
if [ $# -ne 1 ]; then
  echo "Usage: ${0} DEPLOY_ENV"
  echo
  echo "DEPLOY_ENV := { local | production | staging | [ANYTHING] }"
  echo
  echo "HINT: 'local' is a production environment used on localhost"
  exit 1
fi

DEPLOY_ENV=${1}
HOSTS_FILE=/etc/ansible/${DEPLOY_ENV}
PLAYBOOK_FILE="$(dirname $0)/../ansible/$(basename ${0}).yml"

[[ -n "$(which ansible)" ]] || $(dirname $0)/install-ansible

$(dirname $0)/dump-secrets-file # generate secrets file [if does not exist]

if [[ "${DEPLOY_ENV}" == "local" || "${DEPLOY_ENV}" == "production" ]]; then
  APP_VERSION="master"
else
  APP_VERSION="develop"
fi

if [[ "${DEPLOY_ENV}" == "local" ]]; then
  ansible-playbook -c local -i "$(dirname $0)/../ansible/hosts.local" -e app_version=${APP_VERSION} ${PLAYBOOK_FILE}
else
  ansible-playbook -i ${HOSTS_FILE} -e app_version=${APP_VERSION} ${PLAYBOOK_FILE}
fi
