#!/usr/bin/env bash
#
# Reload Rails application server (after code change/re-deploy)
#
SERVICE=cloudport

if [ ${UID} -ne 0 ]; then
  echo "${0} must be run only by root!"
fi

STATUS=$(status cloudport | cut -f2 -d" ")

if [ ${STATUS} == 'start/running,' ]; then
  restart ${SERVICE}
else
  start ${SERVICE}
fi
