#!/usr/bin/env bash
#
# Fetch awesome FamFamFam Silk icons
#
VERSION='v013'
ARCHIVE="famfamfam_silk_icons_${VERSION}.zip"
IMG_DIR="$(dirname ${0})/../../public/images"

set -e

mkdir -p ${IMG_DIR}

pushd ${IMG_DIR}
  [[ -d icons ]] && exit 0

  wget -nv "http://www.famfamfam.com/lab/icons/silk/${ARCHIVE}"

  unzip ${ARCHIVE}

  rm ${ARCHIVE} readme.html readme.txt
popd
