#!/usr/bin/env bash
#
# Fetch awesome FamFamFam Silk icons
#
VERSION='v013'
ARCHIVE="famfamfam_silk_icons_${VERSION}.zip"

set -e

pushd "$(dirname ${0})/../../public/images"
  [[ -d icons ]] && exit 0

  wget "http://www.famfamfam.com/lab/icons/silk/${ARCHIVE}"

  unzip ${ARCHIVE}

  rm ${ARCHIVE} readme.html readme.txt
popd
