#!/usr/bin/env bash
#
# Ensure PID dir exists and has right permissions
#
if [ ${UID} -ne 0 ]; then
  echo "${0} must be run only by root!"
  exit 1
fi

set -e

PID_DIR=/var/run/cloudport

mkdir -p ${PID_DIR}
chown cloudport ${PID_DIR}
chmod 0755 ${PID_DIR}
