#!/usr/bin/env bash
#
# Reload application server and scheduler
# ... after code change/re-deploy ...
#
: ${APP_NAME:=cloudport}

if [ ${UID} -ne 0 ]; then
  echo "${0} must be run only by root!"
  exit 1
fi

set -e

function reload_service() {
  SERVICE=${1}
  COMMAND=${2-'reload'}

  STATUS=$(status ${SERVICE} | cut -f2 -d" " | sed 's/,$//')

  if [ ${STATUS} == 'start/running' ]; then
    ${COMMAND} ${SERVICE}
  else
    start ${SERVICE}
  fi
}

reload_service ${APP_NAME}

reload_service sidekiq 'restart'
